#include <QAction>
#include <QActionGroup>
#include <QApplication>
#include <QString>

#include <iostream>

#include "action_router.h"
#include "business_context.h"
#include "function_registry.h"
#include "register_all_functions.h"
#include "ui_context.h"

int main(int argc, char** argv)
{
    QApplication application(argc, argv);
    BusinessContext business;
    UiContext ui;
    FunctionRegistry registry;

    if (!registerAllFunctions(registry, business) || registry.size() != 200)
        return 3;
    if (registerAllFunctions(registry, business) || registry.size() != 200)
        return 4;

    RouterState state;
    ActionRouter router(registry, ui, state);
    QActionGroup actionGroup(&application);
    actionGroup.setExclusive(false);
    QObject::connect(
        &actionGroup,
        &QActionGroup::triggered,
        &application,
        [&router](QAction* action) { router.dispatch(action); });

    QAction action0;
    action0.setCheckable(true);
    action0.setData(QStringLiteral("feature.000"));
    actionGroup.addAction(&action0);
    action0.trigger();
    QAction action1;
    action1.setCheckable(true);
    action1.setData(QStringLiteral("feature.001"));
    actionGroup.addAction(&action1);
    action1.trigger();
    QAction action2;
    action2.setCheckable(true);
    action2.setData(QStringLiteral("feature.002"));
    actionGroup.addAction(&action2);
    action2.trigger();
    QAction action3;
    action3.setCheckable(true);
    action3.setData(QStringLiteral("feature.003"));
    actionGroup.addAction(&action3);
    action3.trigger();
    QAction action4;
    action4.setCheckable(true);
    action4.setData(QStringLiteral("feature.004"));
    actionGroup.addAction(&action4);
    action4.trigger();
    QAction action5;
    action5.setCheckable(true);
    action5.setData(QStringLiteral("feature.005"));
    actionGroup.addAction(&action5);
    action5.trigger();
    QAction action6;
    action6.setCheckable(true);
    action6.setData(QStringLiteral("feature.006"));
    actionGroup.addAction(&action6);
    action6.trigger();
    QAction action7;
    action7.setCheckable(true);
    action7.setData(QStringLiteral("feature.007"));
    actionGroup.addAction(&action7);
    action7.trigger();
    QAction action8;
    action8.setCheckable(true);
    action8.setData(QStringLiteral("feature.008"));
    actionGroup.addAction(&action8);
    action8.trigger();
    QAction action9;
    action9.setCheckable(true);
    action9.setData(QStringLiteral("feature.009"));
    actionGroup.addAction(&action9);
    action9.trigger();
    QAction action10;
    action10.setCheckable(true);
    action10.setData(QStringLiteral("feature.010"));
    actionGroup.addAction(&action10);
    action10.trigger();
    QAction action11;
    action11.setCheckable(true);
    action11.setData(QStringLiteral("feature.011"));
    actionGroup.addAction(&action11);
    action11.trigger();
    QAction action12;
    action12.setCheckable(true);
    action12.setData(QStringLiteral("feature.012"));
    actionGroup.addAction(&action12);
    action12.trigger();
    QAction action13;
    action13.setCheckable(true);
    action13.setData(QStringLiteral("feature.013"));
    actionGroup.addAction(&action13);
    action13.trigger();
    QAction action14;
    action14.setCheckable(true);
    action14.setData(QStringLiteral("feature.014"));
    actionGroup.addAction(&action14);
    action14.trigger();
    QAction action15;
    action15.setCheckable(true);
    action15.setData(QStringLiteral("feature.015"));
    actionGroup.addAction(&action15);
    action15.trigger();
    QAction action16;
    action16.setCheckable(true);
    action16.setData(QStringLiteral("feature.016"));
    actionGroup.addAction(&action16);
    action16.trigger();
    QAction action17;
    action17.setCheckable(true);
    action17.setData(QStringLiteral("feature.017"));
    actionGroup.addAction(&action17);
    action17.trigger();
    QAction action18;
    action18.setCheckable(true);
    action18.setData(QStringLiteral("feature.018"));
    actionGroup.addAction(&action18);
    action18.trigger();
    QAction action19;
    action19.setCheckable(true);
    action19.setData(QStringLiteral("feature.019"));
    actionGroup.addAction(&action19);
    action19.trigger();
    QAction action20;
    action20.setCheckable(true);
    action20.setData(QStringLiteral("feature.020"));
    actionGroup.addAction(&action20);
    action20.trigger();
    QAction action21;
    action21.setCheckable(true);
    action21.setData(QStringLiteral("feature.021"));
    actionGroup.addAction(&action21);
    action21.trigger();
    QAction action22;
    action22.setCheckable(true);
    action22.setData(QStringLiteral("feature.022"));
    actionGroup.addAction(&action22);
    action22.trigger();
    QAction action23;
    action23.setCheckable(true);
    action23.setData(QStringLiteral("feature.023"));
    actionGroup.addAction(&action23);
    action23.trigger();
    QAction action24;
    action24.setCheckable(true);
    action24.setData(QStringLiteral("feature.024"));
    actionGroup.addAction(&action24);
    action24.trigger();
    QAction action25;
    action25.setCheckable(true);
    action25.setData(QStringLiteral("feature.025"));
    actionGroup.addAction(&action25);
    action25.trigger();
    QAction action26;
    action26.setCheckable(true);
    action26.setData(QStringLiteral("feature.026"));
    actionGroup.addAction(&action26);
    action26.trigger();
    QAction action27;
    action27.setCheckable(true);
    action27.setData(QStringLiteral("feature.027"));
    actionGroup.addAction(&action27);
    action27.trigger();
    QAction action28;
    action28.setCheckable(true);
    action28.setData(QStringLiteral("feature.028"));
    actionGroup.addAction(&action28);
    action28.trigger();
    QAction action29;
    action29.setCheckable(true);
    action29.setData(QStringLiteral("feature.029"));
    actionGroup.addAction(&action29);
    action29.trigger();
    QAction action30;
    action30.setCheckable(true);
    action30.setData(QStringLiteral("feature.030"));
    actionGroup.addAction(&action30);
    action30.trigger();
    QAction action31;
    action31.setCheckable(true);
    action31.setData(QStringLiteral("feature.031"));
    actionGroup.addAction(&action31);
    action31.trigger();
    QAction action32;
    action32.setCheckable(true);
    action32.setData(QStringLiteral("feature.032"));
    actionGroup.addAction(&action32);
    action32.trigger();
    QAction action33;
    action33.setCheckable(true);
    action33.setData(QStringLiteral("feature.033"));
    actionGroup.addAction(&action33);
    action33.trigger();
    QAction action34;
    action34.setCheckable(true);
    action34.setData(QStringLiteral("feature.034"));
    actionGroup.addAction(&action34);
    action34.trigger();
    QAction action35;
    action35.setCheckable(true);
    action35.setData(QStringLiteral("feature.035"));
    actionGroup.addAction(&action35);
    action35.trigger();
    QAction action36;
    action36.setCheckable(true);
    action36.setData(QStringLiteral("feature.036"));
    actionGroup.addAction(&action36);
    action36.trigger();
    QAction action37;
    action37.setCheckable(true);
    action37.setData(QStringLiteral("feature.037"));
    actionGroup.addAction(&action37);
    action37.trigger();
    QAction action38;
    action38.setCheckable(true);
    action38.setData(QStringLiteral("feature.038"));
    actionGroup.addAction(&action38);
    action38.trigger();
    QAction action39;
    action39.setCheckable(true);
    action39.setData(QStringLiteral("feature.039"));
    actionGroup.addAction(&action39);
    action39.trigger();
    QAction action40;
    action40.setCheckable(true);
    action40.setData(QStringLiteral("feature.040"));
    actionGroup.addAction(&action40);
    action40.trigger();
    QAction action41;
    action41.setCheckable(true);
    action41.setData(QStringLiteral("feature.041"));
    actionGroup.addAction(&action41);
    action41.trigger();
    QAction action42;
    action42.setCheckable(true);
    action42.setData(QStringLiteral("feature.042"));
    actionGroup.addAction(&action42);
    action42.trigger();
    QAction action43;
    action43.setCheckable(true);
    action43.setData(QStringLiteral("feature.043"));
    actionGroup.addAction(&action43);
    action43.trigger();
    QAction action44;
    action44.setCheckable(true);
    action44.setData(QStringLiteral("feature.044"));
    actionGroup.addAction(&action44);
    action44.trigger();
    QAction action45;
    action45.setCheckable(true);
    action45.setData(QStringLiteral("feature.045"));
    actionGroup.addAction(&action45);
    action45.trigger();
    QAction action46;
    action46.setCheckable(true);
    action46.setData(QStringLiteral("feature.046"));
    actionGroup.addAction(&action46);
    action46.trigger();
    QAction action47;
    action47.setCheckable(true);
    action47.setData(QStringLiteral("feature.047"));
    actionGroup.addAction(&action47);
    action47.trigger();
    QAction action48;
    action48.setCheckable(true);
    action48.setData(QStringLiteral("feature.048"));
    actionGroup.addAction(&action48);
    action48.trigger();
    QAction action49;
    action49.setCheckable(true);
    action49.setData(QStringLiteral("feature.049"));
    actionGroup.addAction(&action49);
    action49.trigger();
    QAction action50;
    action50.setCheckable(true);
    action50.setData(QStringLiteral("feature.050"));
    actionGroup.addAction(&action50);
    action50.trigger();
    QAction action51;
    action51.setCheckable(true);
    action51.setData(QStringLiteral("feature.051"));
    actionGroup.addAction(&action51);
    action51.trigger();
    QAction action52;
    action52.setCheckable(true);
    action52.setData(QStringLiteral("feature.052"));
    actionGroup.addAction(&action52);
    action52.trigger();
    QAction action53;
    action53.setCheckable(true);
    action53.setData(QStringLiteral("feature.053"));
    actionGroup.addAction(&action53);
    action53.trigger();
    QAction action54;
    action54.setCheckable(true);
    action54.setData(QStringLiteral("feature.054"));
    actionGroup.addAction(&action54);
    action54.trigger();
    QAction action55;
    action55.setCheckable(true);
    action55.setData(QStringLiteral("feature.055"));
    actionGroup.addAction(&action55);
    action55.trigger();
    QAction action56;
    action56.setCheckable(true);
    action56.setData(QStringLiteral("feature.056"));
    actionGroup.addAction(&action56);
    action56.trigger();
    QAction action57;
    action57.setCheckable(true);
    action57.setData(QStringLiteral("feature.057"));
    actionGroup.addAction(&action57);
    action57.trigger();
    QAction action58;
    action58.setCheckable(true);
    action58.setData(QStringLiteral("feature.058"));
    actionGroup.addAction(&action58);
    action58.trigger();
    QAction action59;
    action59.setCheckable(true);
    action59.setData(QStringLiteral("feature.059"));
    actionGroup.addAction(&action59);
    action59.trigger();
    QAction action60;
    action60.setCheckable(true);
    action60.setData(QStringLiteral("feature.060"));
    actionGroup.addAction(&action60);
    action60.trigger();
    QAction action61;
    action61.setCheckable(true);
    action61.setData(QStringLiteral("feature.061"));
    actionGroup.addAction(&action61);
    action61.trigger();
    QAction action62;
    action62.setCheckable(true);
    action62.setData(QStringLiteral("feature.062"));
    actionGroup.addAction(&action62);
    action62.trigger();
    QAction action63;
    action63.setCheckable(true);
    action63.setData(QStringLiteral("feature.063"));
    actionGroup.addAction(&action63);
    action63.trigger();
    QAction action64;
    action64.setCheckable(true);
    action64.setData(QStringLiteral("feature.064"));
    actionGroup.addAction(&action64);
    action64.trigger();
    QAction action65;
    action65.setCheckable(true);
    action65.setData(QStringLiteral("feature.065"));
    actionGroup.addAction(&action65);
    action65.trigger();
    QAction action66;
    action66.setCheckable(true);
    action66.setData(QStringLiteral("feature.066"));
    actionGroup.addAction(&action66);
    action66.trigger();
    QAction action67;
    action67.setCheckable(true);
    action67.setData(QStringLiteral("feature.067"));
    actionGroup.addAction(&action67);
    action67.trigger();
    QAction action68;
    action68.setCheckable(true);
    action68.setData(QStringLiteral("feature.068"));
    actionGroup.addAction(&action68);
    action68.trigger();
    QAction action69;
    action69.setCheckable(true);
    action69.setData(QStringLiteral("feature.069"));
    actionGroup.addAction(&action69);
    action69.trigger();
    QAction action70;
    action70.setCheckable(true);
    action70.setData(QStringLiteral("feature.070"));
    actionGroup.addAction(&action70);
    action70.trigger();
    QAction action71;
    action71.setCheckable(true);
    action71.setData(QStringLiteral("feature.071"));
    actionGroup.addAction(&action71);
    action71.trigger();
    QAction action72;
    action72.setCheckable(true);
    action72.setData(QStringLiteral("feature.072"));
    actionGroup.addAction(&action72);
    action72.trigger();
    QAction action73;
    action73.setCheckable(true);
    action73.setData(QStringLiteral("feature.073"));
    actionGroup.addAction(&action73);
    action73.trigger();
    QAction action74;
    action74.setCheckable(true);
    action74.setData(QStringLiteral("feature.074"));
    actionGroup.addAction(&action74);
    action74.trigger();
    QAction action75;
    action75.setCheckable(true);
    action75.setData(QStringLiteral("feature.075"));
    actionGroup.addAction(&action75);
    action75.trigger();
    QAction action76;
    action76.setCheckable(true);
    action76.setData(QStringLiteral("feature.076"));
    actionGroup.addAction(&action76);
    action76.trigger();
    QAction action77;
    action77.setCheckable(true);
    action77.setData(QStringLiteral("feature.077"));
    actionGroup.addAction(&action77);
    action77.trigger();
    QAction action78;
    action78.setCheckable(true);
    action78.setData(QStringLiteral("feature.078"));
    actionGroup.addAction(&action78);
    action78.trigger();
    QAction action79;
    action79.setCheckable(true);
    action79.setData(QStringLiteral("feature.079"));
    actionGroup.addAction(&action79);
    action79.trigger();
    QAction action80;
    action80.setCheckable(true);
    action80.setData(QStringLiteral("feature.080"));
    actionGroup.addAction(&action80);
    action80.trigger();
    QAction action81;
    action81.setCheckable(true);
    action81.setData(QStringLiteral("feature.081"));
    actionGroup.addAction(&action81);
    action81.trigger();
    QAction action82;
    action82.setCheckable(true);
    action82.setData(QStringLiteral("feature.082"));
    actionGroup.addAction(&action82);
    action82.trigger();
    QAction action83;
    action83.setCheckable(true);
    action83.setData(QStringLiteral("feature.083"));
    actionGroup.addAction(&action83);
    action83.trigger();
    QAction action84;
    action84.setCheckable(true);
    action84.setData(QStringLiteral("feature.084"));
    actionGroup.addAction(&action84);
    action84.trigger();
    QAction action85;
    action85.setCheckable(true);
    action85.setData(QStringLiteral("feature.085"));
    actionGroup.addAction(&action85);
    action85.trigger();
    QAction action86;
    action86.setCheckable(true);
    action86.setData(QStringLiteral("feature.086"));
    actionGroup.addAction(&action86);
    action86.trigger();
    QAction action87;
    action87.setCheckable(true);
    action87.setData(QStringLiteral("feature.087"));
    actionGroup.addAction(&action87);
    action87.trigger();
    QAction action88;
    action88.setCheckable(true);
    action88.setData(QStringLiteral("feature.088"));
    actionGroup.addAction(&action88);
    action88.trigger();
    QAction action89;
    action89.setCheckable(true);
    action89.setData(QStringLiteral("feature.089"));
    actionGroup.addAction(&action89);
    action89.trigger();
    QAction action90;
    action90.setCheckable(true);
    action90.setData(QStringLiteral("feature.090"));
    actionGroup.addAction(&action90);
    action90.trigger();
    QAction action91;
    action91.setCheckable(true);
    action91.setData(QStringLiteral("feature.091"));
    actionGroup.addAction(&action91);
    action91.trigger();
    QAction action92;
    action92.setCheckable(true);
    action92.setData(QStringLiteral("feature.092"));
    actionGroup.addAction(&action92);
    action92.trigger();
    QAction action93;
    action93.setCheckable(true);
    action93.setData(QStringLiteral("feature.093"));
    actionGroup.addAction(&action93);
    action93.trigger();
    QAction action94;
    action94.setCheckable(true);
    action94.setData(QStringLiteral("feature.094"));
    actionGroup.addAction(&action94);
    action94.trigger();
    QAction action95;
    action95.setCheckable(true);
    action95.setData(QStringLiteral("feature.095"));
    actionGroup.addAction(&action95);
    action95.trigger();
    QAction action96;
    action96.setCheckable(true);
    action96.setData(QStringLiteral("feature.096"));
    actionGroup.addAction(&action96);
    action96.trigger();
    QAction action97;
    action97.setCheckable(true);
    action97.setData(QStringLiteral("feature.097"));
    actionGroup.addAction(&action97);
    action97.trigger();
    QAction action98;
    action98.setCheckable(true);
    action98.setData(QStringLiteral("feature.098"));
    actionGroup.addAction(&action98);
    action98.trigger();
    QAction action99;
    action99.setCheckable(true);
    action99.setData(QStringLiteral("feature.099"));
    actionGroup.addAction(&action99);
    action99.trigger();
    QAction action100;
    action100.setCheckable(true);
    action100.setData(QStringLiteral("feature.100"));
    actionGroup.addAction(&action100);
    action100.trigger();
    QAction action101;
    action101.setCheckable(true);
    action101.setData(QStringLiteral("feature.101"));
    actionGroup.addAction(&action101);
    action101.trigger();
    QAction action102;
    action102.setCheckable(true);
    action102.setData(QStringLiteral("feature.102"));
    actionGroup.addAction(&action102);
    action102.trigger();
    QAction action103;
    action103.setCheckable(true);
    action103.setData(QStringLiteral("feature.103"));
    actionGroup.addAction(&action103);
    action103.trigger();
    QAction action104;
    action104.setCheckable(true);
    action104.setData(QStringLiteral("feature.104"));
    actionGroup.addAction(&action104);
    action104.trigger();
    QAction action105;
    action105.setCheckable(true);
    action105.setData(QStringLiteral("feature.105"));
    actionGroup.addAction(&action105);
    action105.trigger();
    QAction action106;
    action106.setCheckable(true);
    action106.setData(QStringLiteral("feature.106"));
    actionGroup.addAction(&action106);
    action106.trigger();
    QAction action107;
    action107.setCheckable(true);
    action107.setData(QStringLiteral("feature.107"));
    actionGroup.addAction(&action107);
    action107.trigger();
    QAction action108;
    action108.setCheckable(true);
    action108.setData(QStringLiteral("feature.108"));
    actionGroup.addAction(&action108);
    action108.trigger();
    QAction action109;
    action109.setCheckable(true);
    action109.setData(QStringLiteral("feature.109"));
    actionGroup.addAction(&action109);
    action109.trigger();
    QAction action110;
    action110.setCheckable(true);
    action110.setData(QStringLiteral("feature.110"));
    actionGroup.addAction(&action110);
    action110.trigger();
    QAction action111;
    action111.setCheckable(true);
    action111.setData(QStringLiteral("feature.111"));
    actionGroup.addAction(&action111);
    action111.trigger();
    QAction action112;
    action112.setCheckable(true);
    action112.setData(QStringLiteral("feature.112"));
    actionGroup.addAction(&action112);
    action112.trigger();
    QAction action113;
    action113.setCheckable(true);
    action113.setData(QStringLiteral("feature.113"));
    actionGroup.addAction(&action113);
    action113.trigger();
    QAction action114;
    action114.setCheckable(true);
    action114.setData(QStringLiteral("feature.114"));
    actionGroup.addAction(&action114);
    action114.trigger();
    QAction action115;
    action115.setCheckable(true);
    action115.setData(QStringLiteral("feature.115"));
    actionGroup.addAction(&action115);
    action115.trigger();
    QAction action116;
    action116.setCheckable(true);
    action116.setData(QStringLiteral("feature.116"));
    actionGroup.addAction(&action116);
    action116.trigger();
    QAction action117;
    action117.setCheckable(true);
    action117.setData(QStringLiteral("feature.117"));
    actionGroup.addAction(&action117);
    action117.trigger();
    QAction action118;
    action118.setCheckable(true);
    action118.setData(QStringLiteral("feature.118"));
    actionGroup.addAction(&action118);
    action118.trigger();
    QAction action119;
    action119.setCheckable(true);
    action119.setData(QStringLiteral("feature.119"));
    actionGroup.addAction(&action119);
    action119.trigger();
    QAction action120;
    action120.setCheckable(true);
    action120.setData(QStringLiteral("feature.120"));
    actionGroup.addAction(&action120);
    action120.trigger();
    QAction action121;
    action121.setCheckable(true);
    action121.setData(QStringLiteral("feature.121"));
    actionGroup.addAction(&action121);
    action121.trigger();
    QAction action122;
    action122.setCheckable(true);
    action122.setData(QStringLiteral("feature.122"));
    actionGroup.addAction(&action122);
    action122.trigger();
    QAction action123;
    action123.setCheckable(true);
    action123.setData(QStringLiteral("feature.123"));
    actionGroup.addAction(&action123);
    action123.trigger();
    QAction action124;
    action124.setCheckable(true);
    action124.setData(QStringLiteral("feature.124"));
    actionGroup.addAction(&action124);
    action124.trigger();
    QAction action125;
    action125.setCheckable(true);
    action125.setData(QStringLiteral("feature.125"));
    actionGroup.addAction(&action125);
    action125.trigger();
    QAction action126;
    action126.setCheckable(true);
    action126.setData(QStringLiteral("feature.126"));
    actionGroup.addAction(&action126);
    action126.trigger();
    QAction action127;
    action127.setCheckable(true);
    action127.setData(QStringLiteral("feature.127"));
    actionGroup.addAction(&action127);
    action127.trigger();
    QAction action128;
    action128.setCheckable(true);
    action128.setData(QStringLiteral("feature.128"));
    actionGroup.addAction(&action128);
    action128.trigger();
    QAction action129;
    action129.setCheckable(true);
    action129.setData(QStringLiteral("feature.129"));
    actionGroup.addAction(&action129);
    action129.trigger();
    QAction action130;
    action130.setCheckable(true);
    action130.setData(QStringLiteral("feature.130"));
    actionGroup.addAction(&action130);
    action130.trigger();
    QAction action131;
    action131.setCheckable(true);
    action131.setData(QStringLiteral("feature.131"));
    actionGroup.addAction(&action131);
    action131.trigger();
    QAction action132;
    action132.setCheckable(true);
    action132.setData(QStringLiteral("feature.132"));
    actionGroup.addAction(&action132);
    action132.trigger();
    QAction action133;
    action133.setCheckable(true);
    action133.setData(QStringLiteral("feature.133"));
    actionGroup.addAction(&action133);
    action133.trigger();
    QAction action134;
    action134.setCheckable(true);
    action134.setData(QStringLiteral("feature.134"));
    actionGroup.addAction(&action134);
    action134.trigger();
    QAction action135;
    action135.setCheckable(true);
    action135.setData(QStringLiteral("feature.135"));
    actionGroup.addAction(&action135);
    action135.trigger();
    QAction action136;
    action136.setCheckable(true);
    action136.setData(QStringLiteral("feature.136"));
    actionGroup.addAction(&action136);
    action136.trigger();
    QAction action137;
    action137.setCheckable(true);
    action137.setData(QStringLiteral("feature.137"));
    actionGroup.addAction(&action137);
    action137.trigger();
    QAction action138;
    action138.setCheckable(true);
    action138.setData(QStringLiteral("feature.138"));
    actionGroup.addAction(&action138);
    action138.trigger();
    QAction action139;
    action139.setCheckable(true);
    action139.setData(QStringLiteral("feature.139"));
    actionGroup.addAction(&action139);
    action139.trigger();
    QAction action140;
    action140.setCheckable(true);
    action140.setData(QStringLiteral("feature.140"));
    actionGroup.addAction(&action140);
    action140.trigger();
    QAction action141;
    action141.setCheckable(true);
    action141.setData(QStringLiteral("feature.141"));
    actionGroup.addAction(&action141);
    action141.trigger();
    QAction action142;
    action142.setCheckable(true);
    action142.setData(QStringLiteral("feature.142"));
    actionGroup.addAction(&action142);
    action142.trigger();
    QAction action143;
    action143.setCheckable(true);
    action143.setData(QStringLiteral("feature.143"));
    actionGroup.addAction(&action143);
    action143.trigger();
    QAction action144;
    action144.setCheckable(true);
    action144.setData(QStringLiteral("feature.144"));
    actionGroup.addAction(&action144);
    action144.trigger();
    QAction action145;
    action145.setCheckable(true);
    action145.setData(QStringLiteral("feature.145"));
    actionGroup.addAction(&action145);
    action145.trigger();
    QAction action146;
    action146.setCheckable(true);
    action146.setData(QStringLiteral("feature.146"));
    actionGroup.addAction(&action146);
    action146.trigger();
    QAction action147;
    action147.setCheckable(true);
    action147.setData(QStringLiteral("feature.147"));
    actionGroup.addAction(&action147);
    action147.trigger();
    QAction action148;
    action148.setCheckable(true);
    action148.setData(QStringLiteral("feature.148"));
    actionGroup.addAction(&action148);
    action148.trigger();
    QAction action149;
    action149.setCheckable(true);
    action149.setData(QStringLiteral("feature.149"));
    actionGroup.addAction(&action149);
    action149.trigger();
    QAction action150;
    action150.setCheckable(true);
    action150.setData(QStringLiteral("feature.150"));
    actionGroup.addAction(&action150);
    action150.trigger();
    QAction action151;
    action151.setCheckable(true);
    action151.setData(QStringLiteral("feature.151"));
    actionGroup.addAction(&action151);
    action151.trigger();
    QAction action152;
    action152.setCheckable(true);
    action152.setData(QStringLiteral("feature.152"));
    actionGroup.addAction(&action152);
    action152.trigger();
    QAction action153;
    action153.setCheckable(true);
    action153.setData(QStringLiteral("feature.153"));
    actionGroup.addAction(&action153);
    action153.trigger();
    QAction action154;
    action154.setCheckable(true);
    action154.setData(QStringLiteral("feature.154"));
    actionGroup.addAction(&action154);
    action154.trigger();
    QAction action155;
    action155.setCheckable(true);
    action155.setData(QStringLiteral("feature.155"));
    actionGroup.addAction(&action155);
    action155.trigger();
    QAction action156;
    action156.setCheckable(true);
    action156.setData(QStringLiteral("feature.156"));
    actionGroup.addAction(&action156);
    action156.trigger();
    QAction action157;
    action157.setCheckable(true);
    action157.setData(QStringLiteral("feature.157"));
    actionGroup.addAction(&action157);
    action157.trigger();
    QAction action158;
    action158.setCheckable(true);
    action158.setData(QStringLiteral("feature.158"));
    actionGroup.addAction(&action158);
    action158.trigger();
    QAction action159;
    action159.setCheckable(true);
    action159.setData(QStringLiteral("feature.159"));
    actionGroup.addAction(&action159);
    action159.trigger();
    QAction action160;
    action160.setCheckable(true);
    action160.setData(QStringLiteral("feature.160"));
    actionGroup.addAction(&action160);
    action160.trigger();
    QAction action161;
    action161.setCheckable(true);
    action161.setData(QStringLiteral("feature.161"));
    actionGroup.addAction(&action161);
    action161.trigger();
    QAction action162;
    action162.setCheckable(true);
    action162.setData(QStringLiteral("feature.162"));
    actionGroup.addAction(&action162);
    action162.trigger();
    QAction action163;
    action163.setCheckable(true);
    action163.setData(QStringLiteral("feature.163"));
    actionGroup.addAction(&action163);
    action163.trigger();
    QAction action164;
    action164.setCheckable(true);
    action164.setData(QStringLiteral("feature.164"));
    actionGroup.addAction(&action164);
    action164.trigger();
    QAction action165;
    action165.setCheckable(true);
    action165.setData(QStringLiteral("feature.165"));
    actionGroup.addAction(&action165);
    action165.trigger();
    QAction action166;
    action166.setCheckable(true);
    action166.setData(QStringLiteral("feature.166"));
    actionGroup.addAction(&action166);
    action166.trigger();
    QAction action167;
    action167.setCheckable(true);
    action167.setData(QStringLiteral("feature.167"));
    actionGroup.addAction(&action167);
    action167.trigger();
    QAction action168;
    action168.setCheckable(true);
    action168.setData(QStringLiteral("feature.168"));
    actionGroup.addAction(&action168);
    action168.trigger();
    QAction action169;
    action169.setCheckable(true);
    action169.setData(QStringLiteral("feature.169"));
    actionGroup.addAction(&action169);
    action169.trigger();
    QAction action170;
    action170.setCheckable(true);
    action170.setData(QStringLiteral("feature.170"));
    actionGroup.addAction(&action170);
    action170.trigger();
    QAction action171;
    action171.setCheckable(true);
    action171.setData(QStringLiteral("feature.171"));
    actionGroup.addAction(&action171);
    action171.trigger();
    QAction action172;
    action172.setCheckable(true);
    action172.setData(QStringLiteral("feature.172"));
    actionGroup.addAction(&action172);
    action172.trigger();
    QAction action173;
    action173.setCheckable(true);
    action173.setData(QStringLiteral("feature.173"));
    actionGroup.addAction(&action173);
    action173.trigger();
    QAction action174;
    action174.setCheckable(true);
    action174.setData(QStringLiteral("feature.174"));
    actionGroup.addAction(&action174);
    action174.trigger();
    QAction action175;
    action175.setCheckable(true);
    action175.setData(QStringLiteral("feature.175"));
    actionGroup.addAction(&action175);
    action175.trigger();
    QAction action176;
    action176.setCheckable(true);
    action176.setData(QStringLiteral("feature.176"));
    actionGroup.addAction(&action176);
    action176.trigger();
    QAction action177;
    action177.setCheckable(true);
    action177.setData(QStringLiteral("feature.177"));
    actionGroup.addAction(&action177);
    action177.trigger();
    QAction action178;
    action178.setCheckable(true);
    action178.setData(QStringLiteral("feature.178"));
    actionGroup.addAction(&action178);
    action178.trigger();
    QAction action179;
    action179.setCheckable(true);
    action179.setData(QStringLiteral("feature.179"));
    actionGroup.addAction(&action179);
    action179.trigger();
    QAction action180;
    action180.setCheckable(true);
    action180.setData(QStringLiteral("feature.180"));
    actionGroup.addAction(&action180);
    action180.trigger();
    QAction action181;
    action181.setCheckable(true);
    action181.setData(QStringLiteral("feature.181"));
    actionGroup.addAction(&action181);
    action181.trigger();
    QAction action182;
    action182.setCheckable(true);
    action182.setData(QStringLiteral("feature.182"));
    actionGroup.addAction(&action182);
    action182.trigger();
    QAction action183;
    action183.setCheckable(true);
    action183.setData(QStringLiteral("feature.183"));
    actionGroup.addAction(&action183);
    action183.trigger();
    QAction action184;
    action184.setCheckable(true);
    action184.setData(QStringLiteral("feature.184"));
    actionGroup.addAction(&action184);
    action184.trigger();
    QAction action185;
    action185.setCheckable(true);
    action185.setData(QStringLiteral("feature.185"));
    actionGroup.addAction(&action185);
    action185.trigger();
    QAction action186;
    action186.setCheckable(true);
    action186.setData(QStringLiteral("feature.186"));
    actionGroup.addAction(&action186);
    action186.trigger();
    QAction action187;
    action187.setCheckable(true);
    action187.setData(QStringLiteral("feature.187"));
    actionGroup.addAction(&action187);
    action187.trigger();
    QAction action188;
    action188.setCheckable(true);
    action188.setData(QStringLiteral("feature.188"));
    actionGroup.addAction(&action188);
    action188.trigger();
    QAction action189;
    action189.setCheckable(true);
    action189.setData(QStringLiteral("feature.189"));
    actionGroup.addAction(&action189);
    action189.trigger();
    QAction action190;
    action190.setCheckable(true);
    action190.setData(QStringLiteral("feature.190"));
    actionGroup.addAction(&action190);
    action190.trigger();
    QAction action191;
    action191.setCheckable(true);
    action191.setData(QStringLiteral("feature.191"));
    actionGroup.addAction(&action191);
    action191.trigger();
    QAction action192;
    action192.setCheckable(true);
    action192.setData(QStringLiteral("feature.192"));
    actionGroup.addAction(&action192);
    action192.trigger();
    QAction action193;
    action193.setCheckable(true);
    action193.setData(QStringLiteral("feature.193"));
    actionGroup.addAction(&action193);
    action193.trigger();
    QAction action194;
    action194.setCheckable(true);
    action194.setData(QStringLiteral("feature.194"));
    actionGroup.addAction(&action194);
    action194.trigger();
    QAction action195;
    action195.setCheckable(true);
    action195.setData(QStringLiteral("feature.195"));
    actionGroup.addAction(&action195);
    action195.trigger();
    QAction action196;
    action196.setCheckable(true);
    action196.setData(QStringLiteral("feature.196"));
    actionGroup.addAction(&action196);
    action196.trigger();
    QAction action197;
    action197.setCheckable(true);
    action197.setData(QStringLiteral("feature.197"));
    actionGroup.addAction(&action197);
    action197.trigger();
    QAction action198;
    action198.setCheckable(true);
    action198.setData(QStringLiteral("feature.198"));
    actionGroup.addAction(&action198);
    action198.trigger();
    QAction action199;
    action199.setCheckable(true);
    action199.setData(QStringLiteral("feature.199"));
    actionGroup.addAction(&action199);
    action199.trigger();

    constexpr long long expected = 360352;
    if (state.checksum != expected
        || state.dispatchCount != 200
        || state.failedDispatchCount != 0
        || state.lastFunctionId != "feature.199")
        return 5;

    QAction unknownAction;
    unknownAction.setData(QStringLiteral("feature.missing"));
    actionGroup.addAction(&unknownAction);
    unknownAction.trigger();
    if (state.checksum != expected
        || state.dispatchCount != 200
        || state.failedDispatchCount != 1
        || state.lastFunctionId != "feature.missing")
        return 6;

    std::cout << "variant=" << BENCH_VARIANT_NAME
              << " count=200 dispatches=" << state.dispatchCount
              << " failed=" << state.failedDispatchCount
              << " checksum=" << state.checksum << '\n';
    return 0;
}
